### PR TITLE
Backported RTCM subscriber and NMEA GGA publisher from ROS2 driver

### PR DESCRIPTION
**Pull request by cledant**
In order to support a third party NTRIP client ROS module, an RTCM subscriber and NMEA GGA publisher were added.  
Those changes were backported from ROS2 driver.

### CODE REVIEW

**Comment by aronasefaw** [comment]
Great work, its really appreciated! However we tried using it for our SBG and encountered some issues, we are publishing the nmea messages and getting the rtcm messages but the corrections doesn't seem to be applied to the right interface as we're not seeing a change is position accuracy? Could it just be a setting we forgot to set in the sbg center that is not available through the config file in the ros driver?

**Comment by cledant** [comment]
It might be a device configuration issue.  
In sbgCenter, when configuring the device, in `Assignment` panel, `RTCM` should be set to `Port A`.

**Comment by asherikov** [comment]
> In sbgCenter, when configuring the device, in `Assignment` panel, `RTCM` should be set to `Port A`.
Warning for other users: this is not possible on some (older?) devices, RTCM is bound to other ports;

Also, `config/example/*.yaml` files should be updated too.
￼

**Comment by rsiryani** [comment]
Hi @asherikov, ELLIPSE-N and ELLIPSE-D can accept RTCM on any port since [firmware 2.2.41-stable](https://support.sbg-systems.com/sc/el/latest/firmware-releases/2-2-41-stable).

It is not related to the hardware but only the firmware that can be easily downloaded and update for free.
The firmware is compatible with all ELLIPSE hardware revisions from 1 to 3.

However, keep in mind that ELLIPSE-N v1/v2 are not RTK capable and will only deliver DGPS if RTCM corrections are fed.

Regards,

**Comment by asherikov** [comment]
@rsiryani , thanks for the feedback, however, I cannot set RTCM aid to anything but port C via sbgCenter, I am playing with Ellipse2-D (firmware 2.4.413-stable, hardware 2.0.0.0), sbgCenter version is 3.5.458-stable. Do I have to set the port via sbgECom?

**Pull request closed without merging**
